apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ib-frontend-service
spec:
  hosts:
  - ib-frontend-service
  http:
  - route:
    - destination:
        host: ib-frontend-service
        subset: v1