apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: accounts-service
spec:
  hosts:
    - accounts-service
  http:
  - route:
    - destination:
        host: accounts-service
        subset: v1
      weight: 50
    - destination:
        host: accounts-service
        subset: v2
      weight: 50